apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Name}}
  labels:
    group: load
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      name: {{.Name}}
  serviceName: {{.Name}}
  replicas: {{RandIntRange .ReplicasMin .ReplicasMax}}
  template:
    metadata:
      labels:
        group: statefulset
        name: {{.Name}}
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: {{.Name}}
        image: k8s.gcr.io/pause:3.1
        ports:
          - containerPort: 80
            name: web
        resources:
          requests:
            cpu: 10m
            memory: "10M"
